swagger: "2.0"
info:
  description: "MangaRock API documentation\nBase URL: https://api.mangarockhd.com/query/web401\n\nAll OIDs are formated `mrs-<type>-<number>`\n\nSee also [how to decode MRI images](https://github.com/poketo/manga-rock-image-decoder/blob/master/lib/decode.js)"
  version: "0.0.1"
  title: "MangaRock API"
host: "cors-anywhere.herokuapp.com"
basePath: "/https://api.mangarockhd.com/query/web401"
tags:
- name: "updated"
  description: "recently updated mangas"
- name: "list"
  description: "list all mangas/authors/etc."
- name: "info"
  description: "get info on an object"
- name: "search"
  description: "search for a specific object"
- name: "read"
  description: "read a chapter (Pages are in an unknown 'MRI' file format that needs decryption)"
- name: "recommendation"
  description: "best to read next"
- name: "unknown"
  description: "not self explaining queries"
schemes:
- "https"
paths:
  /foryou:
    get:
      tags:
      - "unknown"
      summary: "Home page sections and their content"
      description: ""
      parameters:
      - $ref: "#/parameters/msid"
      responses:
        200:
          description: ""
          schema:
            type: "object"
            properties:
              code:
                $ref: "#/definitions/return-code"
              data:
                type: "object"
                properties:
                  tracking_id:
                    type: "string"
                  sections:
                    type: "array"
                    items:
                      type: "object"
                      properties:
                        sectionId:
                          type: "string"
                        title:
                          type: "object"
                          additionalProperties:
                            type: "string"
                        subtitle:
                          type: "object"
                          additionalProperties:
                            type: "string"
                        type:
                          type: "string"
                        items:
                          type: "object"
                          properties:
                            component:
                              type: "string"
                            preview_json_url:
                              type: "string"
                            data:
                              type: "array"
                              items:
                                type: "object"
                                properties:
                                  oid:
                                    type: "string"
                                  title:
                                    type: "object"
                                    additionalProperties:
                                      type: "string"
                                  subtitle:
                                    type: "object"
                                    additionalProperties:
                                      type: "string"
                                  banner_url:
                                    type: "string"
                                  detail_json_url:
                                    type: "string"
                                  cta:
                                    type: "object"
                                    additionalProperties:
                                      type: "string"
                                  items:
                                    type: "array"
                                    items:
                                      type: "string"
                                  oids:
                                    type: "array"
                                    items:
                                      type: "string"
            example:
              code: 0
              data:
                tracking_id: "mra-foryou-13615"
                sections:
                - sectionId: "mra-section-13478"
                  title:
                    en: "Reading Lists "
                  subtitle:
                    en: "Updated Daily "
                  type: "custom"
                  items:
                    component: "StoryBasedItem"
                    preview_json_url: "https://mangarock.com/query/web401/foryou_section_preview?oid=mra-section-13478&country=United+States&ts=1567765515&raw=1"
                    data:
                    - oid: "mrs-collection-200040295"
                      title:
                        en: "The Charm of Being with an Older Girl!"
                      subtitle:
                        en: "It's a commonly accepted… each other's company. "
                      banner_url: ""
                      detail_json_url: "https://mangarock.com/query/web401/legacy_collection?oid=mrs-collection-200040295&country=United+States&ts=1567765515"
                      cta:
                        en: "View now"
                      items:
                      - "631756"
                      oids:
                      - "mrs-serie-100367146"
  /realtime:
    get:
      tags:
      - "unknown"
      summary: "Some liste of manga"
      description: ""
      parameters:
      - $ref: "#/parameters/msid"
      responses:
        200:
          description: ""
          schema:
            type: "object"
            properties:
              code:
                $ref: "#/definitions/return-code"
              data:
                type: "array"
                items:
                  type: "object"
                  properties:
                    mid:
                      type: "integer"
                    name:
                      type: "string"
                    author:
                      type: "string"
                    rank:
                      type: "integer"
                    oid:
                      type: "string"
            example:
              code: 0
              data:
              - mid: 686075
                name: "Metropolitan System"
                author: "Tu Jun"
                rank: 2
                oid: "mrs-serie-200015767"
  /mrs_home_latest:
    get:
      tags:
      - "updated"
      summary: "Latest updates"
      description: ""
      responses:
        200:
          description: ""
          schema:
            type: "object"
            properties:
              code:
                $ref: "#/definitions/return-code"
              data:
                type: "array"
                items:
                  type: "object"
                  properties:
                    oid:
                      type: "string"
                    name:
                      type: "string"
                    genres:
                      type: "array"
                      items:
                        type: "string"
                    rank:
                      type: "integer"
                    updated_chapter:
                      type: "integer"
                    new_chapters:
                      type: "array"
                      items:
                        type: "object"
                        properties:
                          oid:
                            type: "string"
                          name:
                            type: "string"
                          updatedAt:
                            type: "string"
                            format: "date-time"
                    completed:
                      type: "boolean"
                      default: false
                    thumbnail:
                      type: "string"
                      description: "PNG or JPEG"
                    updated_at:
                      type: "string"
                      format: "date-time"
            example:
              code: 0
              data:
              - oid: "mrs-serie-200082321"
                name: "The Strongest War God"
                genres:
                - "mrs-genre-304068"
                rank: 254
                updated_chapters: 1
                new_chapters:
                - oid: "mrs-chapter-200182953"
                  name: "Chapter 80"
                  updatedAt: "2019-10-16T07:12:36Z"
                completed: false
                thumbnail: "https://f01.mrcdn.info/file/mrportal/j/7/7/0/K3.kBUIfi9.png"
                updated_at: "2019-10-16T07:12:36Z"
  /mrs_home_hot_updates:
    $ref: "#/paths/~1mrs_home_latest"
  /mrs_latest:
    $ref: "#/paths/~1mrs_home_latest"
  /mrs_filter:
    post:
      tags:
      - "list"
      summary: "All mangas available on the web site"
      description: ""
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          type: "object"
          properties:
            genres:
              type: "object"
              additionalProperties:
                type: "integer"
                default: 0
            order:
              type: "string"
              default: "rank"
              enum:
              - "rank"
              - "name"
            rank:
              type: "string"
              default: "all"
              enum:
              - "all"
              - "1-999"
              - "1000-2000"
              - "2000-3000"
            status:
              type: "string"
              default: "all"
              enum:
              - "all"
              - "completed"
              - "ongoing"
          example:
            genres: {}
            order: "all"
            rank: "all"
            status: "all"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/list"
  /license:
    get:
      tags:
      - "unknown"
      summary: "some list of mid"
      description: ""
      parameters:
      - $ref: "#/parameters/msid"
      responses:
        200:
          description: ""
          schema:
            type: "object"
            properties:
              code:
                $ref: "#/definitions/return-code"
              data:
                type: "array"
                items:
                  type: "integer"
            example:
              code: 0
              data:
              - 546948
              - 563963
  /mrs_quick_search:
    post:
      tags:
      - "search"
      summary: "search while typing"
      description: ""
      consumes:
      - "text/plain"
      parameters:
      - in: "body"
        name: "query"
        required: true
        schema:
          type: "string"
          example: "one"
      responses:
        200:
          description: ""
          schema:
            type: "object"
            properties:
              code:
                $ref: "#/definitions/return-code"
              data:
                type: "object"
                properties:
                  author:
                    type: "array"
                    items:
                      type: "string"
                  character:
                    type: "array"
                    items:
                      type: "string"
                  serie:
                    type: "array"
                    items:
                      type: "string"
            example:
              code: 0
              data:
                author:
                - "mrs-author-304768"
                character:
                - "mrs-character-342082"
                series:
                - "mrs-serie-221621"
  /mrs_search:
    post:
      tags:
      - "search"
      summary: "full search"
      description: ""
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "object"
          properties:
            keywords:
              type: "string"
            type:
              type: "string"
              enum:
              - "series"
              - "author"
              - "character"
          example:
            keywords: "one"
            type: "series"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/list"
  /manga_detail:
    post:
      tags:
      - "info"
      summary: "query info on one or more manga"
      description: ""
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          type: "object"
          properties:
            oids:
              type: "object"
              properties:
                additionalProperties:
                  type: "integer"
                  default: 0
            sections:
              type: "array"
              items:
                $ref: "#/definitions/section"
          example:
            oids:
              mrs-serie-100159890: 0
            sections:
            - "basic_info"
            - "summary"
            - "artworks"
            - "sub_genres"
            - "social_stats"
            - "author"
            - "character"
            - "publisher"
            - "scanlator"
            - "other_fact"
            - "chapters"
            - "related_series"
            - "same_author"
            - "feature_collections"
      responses:
        200:
          description: ""
          schema:
            type: "object"
            properties:
              code:
                $ref: "#/definitions/return-code"
              data:
                type: "object"
                properties:
                  additionalProperties:
                    type: "object"
                    properties:
                      feature_collections:
                        type: "object"
                        properties:
                          collections:
                            type: "array"
                            items:
                              type: "string"
                      artworks:
                        type: "object"
                        properties:
                          artworks:
                            type: "array"
                            items:
                              type: "string"
                      author:
                        type: "object"
                        properties:
                          authors:
                            type: "array"
                            items:
                              type: "object"
                              properties:
                                oid:
                                  type: "string"
                                role:
                                  type: "string"
                      default:
                        type: "object"
                        properties:
                          oid:
                            type: "string"
                          mid:
                            type: "integer"
                          msid:
                            type: "integer"
                          last_updated:
                            type: "integer"
                      social_stats:
                        type: "object"
                        properties:
                          rank:
                            type: "integer"
                          read:
                            type: "integer"
                      basic_info:
                        type: "object"
                        properties:
                          name:
                            type: "string"
                          thumbnail:
                            type: "string"
                          thumbnail_extra:
                            type: "object"
                            properties:
                              generated:
                                type: "boolean"
                              averageColor:
                                type: "string"
                              textBackgroundColor:
                                type: "string"
                              textColor:
                                type: "string"
                          cover:
                            type: "string"
                          cover_extra:
                              type: "object"
                              properties:
                                generated:
                                  type: "boolean"
                                averageColor:
                                  type: "string"
                                textBackgroundColor:
                                  type: "string"
                                textColor:
                                  type: "string"
                          alias:
                            type: "array"
                            items:
                              type: "string"
                          rank:
                            type: "integer"
                          removed:
                            type: "boolean"
                          author:
                            type: "string"
                          completed:
                            type: "boolean"
                          direction:
                            type: "integer"
                          categories:
                            type: "array"
                            items:
                              type: "integer"
                          total_chapters:
                            type: "integer"
                          description:
                            type: "string"
                          release_frequency:
                            type: "object"
                            properties:
                              type:
                                type: "string"
                              unit:
                                type: "string"
                              amount:
                                type: "integer"
                          mrs_series:
                            type: "string"
                      summary:
                        type: "object"
                        properties:
                          plot_points:
                            type: "array"
                            items:
                              type: "string"
                          key_genres:
                            type: "array"
                            items:
                              type: "string"
                      other_fact:
                        type: "object"
                        properties:
                          extra:
                            type: "object"
                            properties:
                              additionalProperties:
                                type: "string"
                      same_author:
                        type: "object"
                        properties:
                          series:
                            type: "array"
                            items:
                              type: "string"
                      chapters:
                        type: "object"
                        properties:
                          chapters:
                            type: "array"
                            items:
                              type: "object"
                              properties:
                                cid:
                                  type: "integer"
                                oid:
                                  type: "integer"
                                name:
                                  type: "string"
                                last_updated:
                                  type: "integer"
                                order:
                                  type: "integer"
                      sub_genres:
                        type: "object"
                        properties:
                          sub_genres:
                            type: "array"
                            items:
                              type: "string"
            example:
              code: 0
              data:
                mrs-serie-100159890:
                  social_stats:
                    rank: 2
                    read: 49390069
                  artworks:
                    artworks:
                    - "https://f01.mrcdn.info/file/mrportal/j/1/7/8/Qy.4aoOdLRb.jpg"
                  sub_genres:
                    sub_genres:
                    - "mrs-genre-304068"
                  author:
                    authors:
                    - oid: "mrs-author-100171605"
                      role: "art"
                  feature_collections:
                    collections:
                    - "mrs-collection-100384825"
                  chapters:
                    chapters:
                    - cid: 27667050
                      oid: "mrs-chapter-100171588"
                      name: "Chapter 1: Refinement Technique (1)"
                      last_updated: 1517204304
                      order: 0
                  other_fact:
                    extra: {}
                  default:
                    oid: "mrs-serie-100159890"
                    mid: 596702
                    msid: 71
                    last_updated: 1571179977
                  same_author:
                    series:
                    - "mrs-serie-100242638"
                  summary:
                    plot_points:
                    - "After losing the Luo Family's secret heirloom, Luo Zheng has become a mere slave of his own clan"
                    key_genres:
                    - "mrs-genre-304089"
                  basic_info:
                    name: "Apotheosis"
                    thumbnail: "https://f01.mrcdn.info/file/mrportal/j/6/m/e/K3.fAiKDFIT.png"
                    thumbnail_extra:
                      generated: false
                      averageColor: "#BC9592"
                      textBackgroundColor: "#DFBBB9"
                      textColor: "#000000"
                    cover: "https://f01.mrcdn.info/file/mrportal/i/c/e/6/vh.fAfo2i1n.jpg"
                    alias:
                    - "百炼成神"
                    cover_extra:
                      generated: false
                      averageColor: "#C3AAB2"
                      textBackgroundColor: "#D9BFC7"
                      textColor: "#000000"
                    rank: 2
                    removed: false
                    author: "Ranzai Studio"
                    completed: false
                    direction: 0
                    categories:
                    - 1
                    total_chapters: 358
                    description: "Apotheosis - elevation to the status of a god."
                    release_frequency:
                      type: "auto"
                      unit: "day"
                      amount: 1
                    mrs_series: 
  /rec_similar_series_ml:
    get:
      tags:
      - "recommendation"
      summary: "list of recommended manga"
      description: ""
      parameters:
      - $ref: "#/parameters/msid"
      - $ref: "#/parameters/serie-oid"
      responses:
        200:
          description: ""
          schema:
            type: "object"
            properties:
              code:
                $ref: "#/definitions/return-code"
              data:
                type: "array"
                items:
                  type: "object"
                  properties:
                    author:
                      type: "string"
                    mid:
                      type: "integer"
                    name:
                      type: "string"
                    oid:
                      type: "string"
                    status:
                      type: "boolean"
                    total_chapter:
                      type: "integer"
            example:
              code: 0
              data:
              - author: "Shenjoy Animation"
                mid: 603742
                name: "Holy Ancestor"
                oid: "mrs-serie-100203650"
                status: false
                total_chapter: 191
  /rec_because_you_read_ml:
    $ref: "#/paths/~1rec_similar_series_ml"
  /rec_recommendation_ml:
    get:
      tags:
      - "recommendation"
      summary: "list of recommended manga"
      description: ""
      parameters:
      - $ref: "#/parameters/msid"
      responses:
        200:
          $ref: "#/paths/~1rec_similar_series_ml/get/responses/200"
  /rec_btrn:
    get:
      tags:
      - "recommendation"
      summary: "list of recommended manga"
      description: ""
      parameters:
      - $ref: "#/parameters/msid"
      - $ref: "#/parameters/serie-oid"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/list"
  /pagesv2:
    get:
      tags:
      - "read"
      summary: "list of pages of a chapter"
      description: ""
      parameters:
      - $ref: "#/parameters/chapter-oid"
      responses:
        200:
          description: ""
          schema:
            type: "object"
            properties:
              code:
                $ref: "#/definitions/return-code"
              data:
                type: "array"
                items:
                  type: "string"
            example:
              code: 0
              data:
              - url: "https://f01.mrcdn.info/file/mrfiles/j/a/c/3/J-.lQIhAChx.mri"
              - url: "https://f01.mrcdn.info/file/mrfiles/j/a/c/3/JZ.hGQqQWzD.mri"
  /mrs_all_character:
    post:
      tags:
      - "list"
      summary: "list all characters"
      description: ""
      parameters:
      - $ref: "#/parameters/name"
      responses:
        200:
          description: ""
          schema:
            type: "object"
            properties:
              code:
                $ref: "#/definitions/return-code"
              data:
                type: "array"
                items:
                  type: "string"
            example:
              code: 0
              data:
              - "mrs-character-344901"
              - "mrs-character-100166357"
  /character:
    get:
      tags:
      - "info"
      summary: "information on a character"
      description: ""
      parameters:
      - $ref: "#/parameters/character-oid"
      responses:
        200:
          description: ""
          schema:
            type: "object"
            properties:
              code:
                $ref: "#/definitions/return-code"
              data:
                $ref: "#/definitions/bio"
            example:
              code: 0
              data:
                oid: "mrs-character-344901"
                name: "A-ya"
                bio: "A pessimistic boy with black messy hair and red sanpaku eyes."
                thumbnail: "https://f01.mrcdn.info/file/mrportal/h/7/m/j/l6.6JlbhgXy.png"
                artworks:
                - "https://f01.mrcdn.info/file/mrportal/h/5/q/2/Qc.cjYJanqV.jpg"
                extra: {}
  /mrs_serie_related_character:
    get:
      tags:
      - "info"
      summary: "characters related to another"
      description: ""
      parameters:
      - $ref: "#/parameters/character-oid"
      responses:
        200:
          description: ""
          schema:
            type: "object"
            properties:
              code:
                $ref: "#/definitions/return-code"
              data:
                type: "array"
                items:
                  type: "object"
                  properties:
                    mid:
                      type: "integer"
                    oid:
                      type: "string"
            example:
              code: 0
              data:
              - mid: 655314
                oid: "mrs-serie-100438199"
  /mrs_all_author:
    post:
      tags:
      - "list"
      summary: "list all authors"
      description: ""
      parameters:
      - $ref: "#/parameters/name"
      responses:
        200:
          description: ""
          schema:
            type: "object"
            properties:
              code:
                $ref: "#/definitions/return-code"
              data:
                type: "array"
                items:
                  type: "string"
            example:
              code: 0
              data:
              - "mrs-author-100015717"
              - "mrs-author-100031292"
  /author:
    get:
      tags:
      - "info"
      summary: "information on an author"
      description: ""
      parameters:
      - $ref: "#/parameters/author-oid"
      responses:
        200:
          description: ""
          schema:
            type: "object"
            properties:
              code:
                $ref: "#/definitions/return-code"
              data:
                $ref: "#/definitions/bio"
            example:
              code: 0
              data:
                oid: "mrs-author-100171605"
                name: "Ranzai Studio"
                bio: "<p>Series's copyright owner</p>"
                thumbnail: "https://f01.mrcdn.info/file/mrportal/i/c/3/k/nA.2wJJaecA.png"
                artworks: []
                extra: {}
  /genre:
    get:
      tags:
      - "info"
      summary: "information on a genre"
      description: ""
      parameters:
      - $ref: "#/parameters/genre-oid"
      responses:
        200:
          description: ""
          schema:
            type: "object"
            properties:
              code:
                $ref: "#/definitions/return-code"
              data:
                type: "object"
                properties:
                  oid:
                    type: "string"
                  name:
                    type: "string"
                  description:
                    type: "string"
                  cover:
                    type: "string"
                  series:
                    type: "array"
                    items:
                      type: "string"
            example:
              code: 0
              data:
                oid: "mrs-genre-304068"
                name: "Action"
                description: "<div>The action genre in manga depicts extremely high levels of high-intensity action.</div>"
                cover: "https://f01.mrcdn.info/file/mrportal/h/5/g/a/NH.a-CMTVdd.jpg"
                series:
                - "mrs-serie-132938"
  /mrs_serie_related_author:
    get:
      tags:
      - "info"
      summary: "mangas related to an author"
      description: ""
      parameters:
      - $ref: "#/parameters/author-oid"
      responses:
        200:
          description: ""
          schema:
            type: "object"
            properties:
              code:
                $ref: "#/definitions/return-code"
              data:
                type: "array"
                items:
                  type: "object"
                  properties:
                    mid:
                      type: "integer"
                    oid:
                      type: "string"
            example:
              code: 0
              data:
              - mid: 609962
                oid: "mrs-serie-100242638"
  /collection:
    get:
      tags:
      - "info"
      summary: "information on a collection"
      description: ""
      parameters:
      - $ref: "#/parameters/collection-oid"
      responses:
        200:
          description: ""
          schema:
            type: "object"
            properties:
              code:
                $ref: "#/definitions/return-code"
              data:
                type: "object"
                properties:
                  oid:
                    type: "string"
                  name:
                    type: "string"
                  description:
                    type: "string"
                  banner:
                    type: "string"
                  header_type:
                    type: "string"
                  header_data:
                    type: "object"
                    properties:
                      type:
                        type: "string"
                  items_layout:
                    type: "string"
                  items:
                    type: "array"
                    items:
                      type: "object"
                      properties:
                        oid:
                          type: "string"
                        order:
                          type: "integer"
                        data:
                          type: "object"
                  items_type:
                    type: "string"
                  json_file:
                    type: "string"
                  updated_at:
                    type: "string"
            example:
              code: 0
              data:
                oid: "mrs-collection-100384825"
                name: "Best Martial Art Of January"
                description: "Have you ever felt so weak and helpless that ..."
                banner: "https://f01.mrcdn.info/file/mrportal/i/c/o/8/dB.6pKTAFcz.jpg"
                header_type: "story"
                header_data:
                  type: "story"
                item_layout: "grid"
                items:
                - oid: "mrs-serie-100055928"
                  order: 0
                  data: null
                item_type: "serie"
                json_file: "https://mangarock.com/query/android401/legacy_collection?oid=mrs-collection-100384825&country=Definitive"
                updated_at: "2019-02-27T08:12:37Z"
  /../../meta:
    post:
      tags:
      - "info"
      summary: "quick info about objects"
      description: ""
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "array"
          items:
            type: "string"
          example:
          - "mrs-serie-100159890"
          - "mrs-chapter-200179435"
          - "mrs-genre-304068"
          - "mrs-character-100438749"
          - "mrs-collection-100384825"
          - "mrs-author-100171605"
      responses:
        200:
          description: ""
          schema:
            type: "object"
            properties:
              code:
                $ref: "#/definitions/return-code"
              data:
                type: "object"
                additionalProperties:
                  type: "object"
                  properties:
                    oid:
                      type: "string"
                    name:
                      type: "string"
                  additionalProperties: true
            example:
              code: 0
              data:
                mrs-serie-100159890:
                  author_ids:
                  - "mrs-author-100171605"
                  completed: false
                  name: "Apotheosis"
                  oid: "mrs-serie-100159890"
                  thumbnail: "https://f01.mrcdn.info/file/mrportal/j/6/m/e/K3.fAiKDFIT.png"
                  total_chapters: 358
                mrs-chapter-200179435:
                  name: "Vol.TBD Chapter 178: Even if You Reach Out Your Hand"
                  oid: "mrs-chapter-200179435"
                  series_oid: "mrs-serie-132938"
                  total_pages: 19
                mrs-genre-304068:
                  name: "Action"
                  oid: "mrs-genre-304068"
                mrs-character-100438749:
                  name: "Adachi"
                  oid: "mrs-character-100438749"
                  thumbnail: "https://f01.mrcdn.info/file/mrportal/j/3/c/0/k.1WkePPc9.png"
                mrs-collection-100384825:
                  banner: "https://f01.mrcdn.info/file/mrportal/i/c/o/8/dB.6pKTAFcz.jpg"
                  items:
                  - "mrs-serie-22205"
                  name: "Best Martial Art Of January"
                  oid: "mrs-collection-100384825"
                mrs-author-100171605:
                  name: "Ranzai Studio"
                  oid: "mrs-author-100171605"
                  thumbnail: "https://f01.mrcdn.info/file/mrportal/i/c/3/k/nA.2wJJaecA.png"
parameters:
  msid:
    in: "query"
    name: "msid"
    description: ""
    required: true
    type: "integer"
    default: 71
  serie-oid:
    in: "query"
    name: "oid"
    description: ""
    required: true
    type: "string"
    pattern: "mrs-serie-\\d+"
    default: "mrs-serie-100159890"
  chapter-oid:
    in: "query"
    name: "oid"
    description: ""
    required: true
    type: "string"
    pattern: "mrs-chapter-\\d+"
    default: "mrs-chapter-200179435"
  genre-oid:
    in: "query"
    name: "oid"
    description: ""
    required: true
    type: "string"
    pattern: "mrs-genre-\\d+"
    default: "mrs-genre-304068"
  character-oid:
    in: "query"
    name: "oid"
    description: ""
    required: true
    type: "string"
    pattern: "mrs-character-\\d+"
    default: "mrs-character-100438749"
  collection-oid:
    in: "query"
    name: "oid"
    description: ""
    required: true
    type: "string"
    pattern: "mrs-collection-\\d+"
    default: "mrs-collection-100384825"
  author-oid:
    in: "query"
    name: "oid"
    description: ""
    required: true
    type: "string"
    pattern: "mrs-author-\\d+"
    default: "mrs-author-100171605"
  name:
    in: "body"
    name: "body"
    description: "restrict list (blank for all)"
    required: true
    schema:
      type: "object"
      properties:
        name:
          type: "string"
          pattern: "[A-Z]?"
          default: ""
      example:
        name: "A"
definitions:
  return-code:
    type: "integer"
    default: 0
  list:
    type: "object"
    properties:
      code:
        $ref: "#/definitions/return-code"
      data:
        type: "array"
        items:
          type: "string"
    example:
      code: 0
      data:
      - "mrs-serie-200082321"
  bio:
    type: "object"
    properties:
      oid:
        type: "string"
      name:
        type: "string"
      bio:
        type: "string"
      thumbnail:
        type: "string"
      artworks:
        type: "array"
        items:
          type: "string"
      extras:
        type: "object"
        additionalProperties:
          type: "string"
  section:
    type: "string"
    enum:
    - "basic_info"
    - "summary"
    - "artworks"
    - "sub_genres"
    - "social_stats"
    - "author"
    - "character"
    - "publisher"
    - "scanlator"
    - "other_fact"
    - "chapters"
    - "related_series"
    - "same_author"
    - "feature_collections"
